USE DATABASE FEATURESTORE_DB;
USE SCHEMA FEATURESTORE_SCHEMA;
USE ROLE FEATURESTORE_ROLE;

CREATE OR REPLACE PROCEDURE SP_FD_PARAMETER_TABLES("LAYER" VARCHAR)
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS ' 
BEGIN

    IF (UPPER(LAYER) IN (''SILVER'', ''ALL'')) THEN
        CREATE OR REPLACE TABLE SILVER_FD_PARAMETER_CLEAN(
            T_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
            FIXED_ACIDITY FLOAT,
            VOLATILE_ACIDITY FLOAT,
            CITRIC_ACID FLOAT,
            RESIDUAL_SUGAR FLOAT,
            CHLORIDES FLOAT,
            FREE_SULFER_DIOXIDE FLOAT,
            TOTAL_SULFER_DIOXIDE FLOAT,
            DENSITY FLOAT,
            PH FLOAT,
            SULPHATES FLOAT,
            ALCOHOL FLOAT,
            QUALITY INT
        );
    END IF;

    IF (UPPER(LAYER) IN (''GOLD'', ''ALL'')) THEN
        CREATE OR REPLACE TABLE GOLD_FD_PARAMETER_OTHER(
            T_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
            CITRIC_ACID FLOAT NOT NULL,
            RESIDUAL_SUGAR FLOAT NOT NULL,
            CHLORIDES FLOAT NOT NULL,
            DENSITY FLOAT NOT NULL,
            PH FLOAT NOT NULL,
            SULPHATES FLOAT NOT NULL,
            ALCOHOL FLOAT NOT NULL
        );
        CREATE OR REPLACE TABLE GOLD_FD_PARAMETER_ACIDITY(
            T_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
            FIXED_ACIDITY FLOAT,
            VOLATILE_ACIDITY FLOAT,
            SUM_ACIDITY FLOAT NOT NULL,
            AVG_ACIDITY FLOAT NOT NULL
        );
        CREATE OR REPLACE TABLE GOLD_FD_PARAMETER_DIOXIDE(
            T_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
            FREE_SULFER_DIOXIDE FLOAT NOT NULL,
            TOTAL_SULFER_DIOXIDE FLOAT NOT NULL,
            SUM_DIOXIDE FLOAT NOT NULL,
            AVG_DIOXIDE FLOAT NOT NULL
        );
    END IF;
    RETURN CONCAT(''Created Tables for '', LAYER, '' LAYER(s)'');
END';